# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'thesportsdb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for thesportsdb
    pod 'Alamofire', '~> 4.7.3'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'SwiftyJSON', '~> 4.2.0'
    pod 'AlamofireImage', '~> 3.4.1'

  target 'thesportsdbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'thesportsdbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
